DoCoMo: '/^DoCoMo/'
SoftBank: '/^(J\-PHONE|Vodafone|SoftBank|MOT\-)/'
AU: '/^(KDDI\-|UP\.Browser)/'
iPhone: '/^Mozilla\/\d\.\d \(iPhone\;( U\;)? CPU (iPhone OS)?/'
iPad: '/^Mozilla\/\d\.\d \(iPad\;( U\;)? CPU OS/'
Android: '/^Mozilla\/\d\.\d \(Linux\;( U\;)? Android/'
WindowsPhone: '/^Mozilla\/\d\.\d \(compatible; MSIE \d\.\d;( Windows Phone OS|.* Windows Phone \d(\.\d){1,3}\)$)/'
BlackBerry: '/^(BlackBerry\d{4}\/|Mozilla\/\d\.\d \(BlackBerry\;( U;)? BlackBerry)/'
Symbian: '/^(Mozilla\/\d\.\d (\(Symbian\/\d\;|\(SymbianOS\/\d\.\d;)|Nokia\d{1,4}\/\d\.\d)/'
