Category:
  DoCoMo: FeaturePhone
  SoftBank: FeaturePhone
  AU: FeaturePhone
  iPhone: SmartPhone
  iPad: SmartPhone
  Android: SmartPhone
  WindowsPhone: SmartPhone
  BlackBerry: SmartPhone
  MozillaFirefox: OtherDevice
  GoogleChrome: OtherDevice
  Safari: OtherDevice
Type:
  DoCoMo: '/^DoCoMo/'
  SoftBank: '/^(J\-PHONE|Vodafone|SoftBank|MOT\-)/'
  AU: '/^(KDDI\-|UP\.Browser)/'
  iPhone: '/^Mozilla\/(\.?\d)+ \(iPhone\; ([^\s]+ )?CPU (iPhone OS [^\s]+ )?like Mac OS X/'
  iPad: '/^Mozilla\/(\.?\d)+ \(iPad\; ([^\s]+ )?CPU OS/'
  Android: '/^Mozilla\/(\.?\d)+ \(Linux\; ([^\s]+ )?Android/'
  WindowsPhone: '/^Mozilla\/(\.?\d)+ \(compatible; MSIE \d\.\d;( Windows Phone OS|.* Windows Phone \d(\.\d){1,3}\)$)/'
  BlackBerry: '/^(BlackBerry\d{4}\/|Mozilla\/\d\.\d \(BlackBerry\;( U;)? BlackBerry)/'
  Symbian: '/^(Mozilla\/(\.?\d)+ (\(Symbian\/\d\;|\(SymbianOS\/\d\.\d;)|Nokia\d{1,4}\/\d\.\d)/'
  MozillaFirefox: '/^Mozilla\/(\.?\d)+ \([^)]+\) Gecko\/[^\s]+ Firefox\/.+$/'
  GoogleChrome: '/^Mozilla\/(\.?\d)+ \([^)]+\) AppleWebKit\/[^\s]+ \([^)]+\) ([^\s]+ ){0,2}Chrome\/.+$/'
  Safari: '/^Mozilla\/(\.?\d)+ \([^)]+\) AppleWebKit\/[^\s]+ \([^)]+\) (Version\/[^\s]+ )?Safari\/.+$/'
Version:
  iPhone: '/\(iPhone\;\s?[^\s]* CPU\s?((iPhone OS) ([^_]+_[^_]+_?\d{0,}))* like Mac OS X[^\)]*\)/'
  iPad: '/\(iPad\;\s?[^\s]* CPU\s?((OS) ([^_]+_[^_]+_?\d{0,}))* like Mac OS X[^\)]*\)/'
  Android: '/\(Linux\;\s?[^\s]* ((Android) ([^\.]+\.\d{1,}+\.?\d{0,}))\;/'
  MozillaFirefox: '/\s+Gecko\/[^\s]+ ((Firefox)\/([^\.]+\.[^\.]+\.?\d{0,}\.?\d{0,}))/'
  GoogleChrome: '/\s+((Chrome)\/([^\.]+\.[^\.]+\.[^\.]+\.\d{1,}))/'
  Safari: '/\s+((Safari)\/(\d{1,}\.?\d{0,}\.?\d{0,}))$/'