- 'Phpingguo\System\Variable\Session'
- 'Phpingguo\System\Request\Request'
- 'Phpingguo\System\Request\RequestParser'
- 'Phpingguo\System\Filter\Pre\FilterHost'
- 'Phpingguo\System\Filter\Post\FilterHost'
- 'Phpingguo\System\Filter\Input\FilterHost'
- 'Phpingguo\System\Filter\Output\FilterHost'
- 'Phpingguo\System\Generator\GeneratorProxy'
