- 'Phpeel\System\Variable\Session'
- 'Phpeel\System\Request\Request'
- 'Phpeel\System\Request\RequestParser'
- 'Phpeel\System\Filter\Pre\FilterHost'
- 'Phpeel\System\Filter\Post\FilterHost'
- 'Phpeel\System\Filter\Input\FilterHost'
- 'Phpeel\System\Filter\Output\FilterHost'
- 'Phpeel\System\Generator\GeneratorProxy'
