HTML:
  wrapper:
    TWIG:
      options:
        DebugMode: true
        Recompile: true
        AutoEscape: true
    SMARTY:
      options:
        DebugMode: true
        LeftDelimiter: '{{'
        RightDelimiter: '}}'
XML:
  options:
    SuperParentName: 'xml_body'
    DefaultListItemName: 'list_item'
JSON:
  options:
    - JSON_PRETTY_PRINT
    - JSON_UNESCAPED_SLASHES
