HTML:
  class: 'Phpingguo\System\Generator\Html\ContentGenerator'
  wrapper:
    TWIG:
      class: 'Phpingguo\System\Generator\Html\Engine\TwigProxy'
    SMARTY:
      class: 'Phpingguo\System\Generator\Html\Engine\SmartyProxy'
XML:
  class: 'Phpingguo\System\Generator\Xml\ContentGenerator'
JSON:
  class: 'Phpingguo\System\Generator\Json\ContentGenerator'
  options:
    - JSON_PRETTY_PRINT
    - JSON_UNESCAPED_SLASHES